[package]
name = "fleez_api_test"
version = "0.1.0"
authors = ["empea-careercriminal <empeamtk@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
